### ISSUE TITLE
Merge时在obb_nms遇到bug应该怎么解决？

### ISSUE THREAD

**Issue by Virusxxxxxxx** [SJTU-Thinklab-Det/r3det-pytorch#1]
当我调用test.py测试rretinanet_obb_r50_fpn_1x_dota_v3时，总是在Merging patch这一步卡住，经过调试我发现是在nms_rotated_wrapper.py的40行出的问题，上面的注释也写了可能会出现问题，请问我怎么解决这个bug？万分感谢。

**Comment by Virusxxxxxxx** [comment]
问题已解决。
解决方法：```r3det/datasets/dota1.py```的247行，我把4改成了1。

顺便记录一下test v2遇到一个问题```RuntimeError: Cannot re-initialize CUDA in forked subprocess. ```
解决方法：在```test.py```调用```main()```之前，加一句```torch.multiprocessing.set_start_method('spawn')```

**Comment by zytx121** [comment]
Thanks for your question! It looks like you have solved it by yourself.  We will fix this bug in `r3det/datasets/dota1.py`.
