### ISSUE TITLE
when i did the train, I dound the follow quentions:

### ISSUE THREAD

**Issue by rhj0103** [SJTU-Thinklab-Det/r3det-pytorch#11]
ValueError: need at least one array to concatenate

**Comment by yangxue0827** [comment]
please use [mmrotate](https://github.com/open-mmlab/mmrotate) instead.

**Comment by rhj0103** [comment]
我的数据集是个根据BboxToolkit工具处理的，数据将路径正确。
此外，还有请问现在发布的代码模型是rretinanet吗？如果训练r3det只修改cfg文件就可以？

**Comment by yangxue0827** [comment]
solved in https://github.com/open-mmlab/mmrotate/issues/35
