### ISSUE TITLE
ERROR: Command errored out with exit status 1:    develop --no-deps Check the logs for full command output.

### ISSUE THREAD

**Issue by rhj0103** [SJTU-Thinklab-Det/r3det-pytorch#4]
PS D:\任慧娟\python\r3det-pytorch-main> pip install -v -e .             
Using pip 21.3.1 from D:\program\anaconda\lib\site-packages\pip-21.3.1-py3.8.egg\pip (python 3.8)
WARNING: Ignoring invalid distribution -ip (d:\program\anaconda\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\program\anaconda\lib\site-packages)
Obtaining file:///D:/%E4%BB%BB%E6%85%A7%E5%A8%9F/python/r3det-pytorch-main
  Running command python setup.py egg_info
  running egg_info
  creating C:\Users\zqdell\AppData\Local\Temp\pip-pip-egg-info-2wem_6cv\r3det.egg-info
  writing manifest file 'C:\Users\zqdell\AppData\Local\Temp\pip-pip-egg-info-2wem_6cv\r3det.egg-info\SOURCES.txt'
  writing manifest file 'C:\Users\zqdell\AppData\Local\Temp\pip-pip-egg-info-2wem_6cv\r3det.egg-info\SOURCES.txt'
  D:\program\anaconda\lib\site-packages\torch\utils\cpp_extension.py:335: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils b
ackend.
    warnings.warn(msg.format('we could not find ninja.'))
  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "D:\program\anaconda\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
      return stream.closed
  ValueError: underlying buffer has been detached
  Preparing metadata (setup.py) ... done
  WARNING: Ignoring invalid distribution -ip (d:\program\anaconda\lib\site-packages)
Requirement already satisfied: matplotlib in d:\program\anaconda\lib\site-packages (from r3det==0.1.0) (3.3.2)
Requirement already satisfied: numpy in d:\program\anaconda\lib\site-packages (from r3det==0.1.0) (1.19.2)
Installing collected packages: r3det
  Running setup.py develop for r3det
    Running command 'D:\program\anaconda\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\任慧娟\\python\\r3det-pytorch-main\\setup.py'"'"'; __file__='"'"'D:\\任慧娟\\python\\r3det
-pytorch-main\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"
'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\任慧娟\python\r3det-pytorch-main\setup.py", line 177, in <module>
        add_mim_extension()
      File "D:\任慧娟\python\r3det-pytorch-main\setup.py", line 164, in add_mim_extension
        os.symlink(src_relpath, tar_path)
    OSError: [WinError 1314] 客户端没有所需的特权。: '..\\..\\tools' -> 'D:\\任慧娟\\python\\r3det-pytorch-main\\r3det\\.mim\\tools'

ERROR: Command errored out with exit status 1: 'D:\program\anaconda\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\任慧娟\\python\\r3det-pytorch-main\\setup.py'"'"'; __file__='"'
"'D:\\任慧娟\\python\\r3det-pytorch-main\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f
.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
WARNING: Ignoring invalid distribution -ip (d:\program\anaconda\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (d:\program\anaconda\lib\site-packages)

**Comment by zytx121** [comment]
This is caused by MIM. You can delete this [line](https://github.com/SJTU-Thinklab-Det/r3det-pytorch/blob/main/setup.py#L177).

BTW, we haven't tested on the Windows system before.  Linux is recommended.

**Comment by rhj0103** [comment]
Thank you very much. But, how can I delete this line? I just executed "PIP install - V - e." This sentence. Also, can you tell the code running environment?

**Comment by zytx121** [comment]
I fix this bug in the latest version, now you can directly execute "pip install - v - e .".
The running environment is the same with mmdetection.

**Comment by rhj0103** [comment]
Thank you. Do I need to download the code again?

**Comment by rhj0103** [comment]
Thank you. Do I need to download the code again?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SJTU-Thinklab-Det/r3det-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月25日(星期六) 上午9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SJTU-Thinklab-Det/r3det-pytorch] ERROR: Command errored out with exit status 1:    develop --no-deps Check the logs for full command output. (Issue #4)





 
I fix this bug in the latest version, now you can directly execute "pip install - v - e .".
 The running environment is the same with mmdetection.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zytx121** [comment]
Yes, you need to pull the latest code.
