### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by sylarwcy** [SJTU-Thinklab-Det/r3det-pytorch#7]
For DOTA dataset, please crop the original images into 1024×1024 patches with an overlap of 200 by run

python tools/split/img_split.py --base_json \
       tools/split/split_configs/~~split_configs~~/dota1_0/ss_trainval.json

python tools/split/img_split.py --base_json \
       tools/split/split_configs/dota1_0/ss_test.json

**Comment by zytx121** [comment]
THX, I will fix it.
